# Generated by Django 5.2.7 on 2025-11-02 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('contributor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contributor_name', models.CharField(max_length=255)),
                ('age_range', models.CharField(blank=True, help_text="e.g., '18-25', '26-35'", max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contributor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('recording_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_rec_link', models.CharField(blank=True, help_text='Path to raw recording file', max_length=512)),
                ('clean_rec_link', models.CharField(blank=True, help_text='Path to clean recording file', max_length=512)),
                ('ogk_transcription', models.CharField(blank=True, help_text='Transcription in original language', max_length=10000, null=True)),
                ('eng_transcription', models.CharField(blank=True, help_text='Transcription in English', max_length=10000, null=True)),
                ('rec_theme', models.CharField(blank=True, help_text='Theme of the recording', max_length=255, null=True)),
                ('rec_duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(db_column='contributor_id', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='api.contributor')),
            ],
            options={
                'db_table': 'recording',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
